# Cloudflare wrangler configuration https://developers.cloudflare.com/workers/wrangler/configuration/
name = "jbenninghoff-com"
pages_build_output_dir = "public"
compatibility_date = "2026-01-07"

[vars]
HUGO_VERSION = "0.154.3"
